version: 0.2

phases:
  install:
    commands:
      - echo "Installing..."
  build:
    commands:
      - echo "Building app..."
      - mkdir build-artifact
      - shopt -s extglob
      - cp -r !(build-artifact) build-artifact/

artifacts:
  files:
    - '**/*'
  base-directory: build-artifact
