version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Build started on `date`
      - mkdir -p build
      - rsync -av --progress ./ ./build --exclude build

artifacts:
  files:
    - '**/*'
  base-directory: build
