version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
      - mkdir -p build
      - shopt -s extglob
      - cp -r !(build) build/
artifacts:
  files:
    - '**/*'
  base-directory: build
